# ==============================================================
# PROFIL PRODUCTION (Infomaniak Cloud)
# Ce fichier est active uniquement via le profil "prod"
# ==============================================================

# Configuration de la connexion a la base de donnees MySQL sur Alwaysdata
spring.datasource.url=jdbc:mysql://mysql-honeygroupitmada.alwaysdata.net/honeygroupitmada_honeyhub?useSSL=false&serverTimezone=UTC
spring.datasource.username=honeygroupitmada_faty
spring.datasource.password=ra7ma123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuration JPA / Hibernate
# Mode "update" pour permettre l'evolution du schema sans risquer la perte de donnees
# Desactivation de l'affichage SQL pour optimiser les performances et la securite en prod
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Configuration du serveur
# Port d'ecoute de l'application sur l'infrastructure cloud
server.port=8080