# 1. Nom de l'application
spring.application.name=HoneyHub

# 2. Connexion à la base de données Infomaniak
# Remplace [HOTE] par ton adresse (ex: ao7dv.myd.infomaniak.com)
#spring.datasource.url=jdbc:mysql://ao7dvw.myd.infomaniak.com:3306/ao7dvw_HoneyGroup_DB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# On vise ton MySQL local
spring.datasource.url=jdbc:mysql://localhost:3306/ao7dvw_HoneyGroup_DB?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456


# 3. Identifiants de l'utilisateur de l'équipe (ou le tien)
#spring.datasource.username=ao7dvw_ENI_team
#spring.datasource.password=

# 4. Configuration JPA / Hibernate
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
# Utilise le dialecte MySQL 8 car Infomaniak utilise des versions récentes
# Avant : spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
# Maintenant (pour Hibernate 7+) :
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 5. Stratégie de mise à jour (Très important)
# 'validate' vérifie que les tables que nous avons créées par script SQL correspondent bien à ton code Java
#spring.jpa.hibernate.ddl-auto=validate
# On laisse Hibernate créer les tables pour le test local
spring.jpa.hibernate.ddl-auto=update

# 6. Debug : Affiche les requêtes SQL dans la console d'Eclipse
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true